namespace MRSDrunk.Api.DTOs;

public sealed record NominaEmpleadoDto(
    int Id,
    int EmpresaId,
    string TipoDocumento,
    string NumeroDocumento,
    DateTime? FechaExpedicionDocumento,
    string PrimerNombre,
    string? SegundoNombre,
    string PrimerApellido,
    string? SegundoApellido,
    string NombreCompleto,
    string? Documento,
    DateTime? FechaNacimiento,
    string? Genero,
    string? EstadoCivil,
    string? Telefono,
    string? Correo,
    string? Direccion,
    string? Departamento,
    string? Municipio,
    string Pais,
    string? Cargo,
    DateTime FechaIngreso,
    DateTime? FechaRetiro,
    string TipoContrato,
    string TipoTrabajador,
    string SubtipoCotizante,
    string TipoSalario,
    bool SalarioIntegral,
    decimal SalarioBase,
    decimal ValorDiaBase,
    string PeriodicidadPago,
    string JornadaLaboral,
    string? Eps,
    string? FondoPension,
    string? FondoCesantias,
    string? Arl,
    string NivelRiesgoArl,
    string? CajaCompensacion,
    string? Banco,
    string? TipoCuenta,
    string? NumeroCuenta,
    string? ContactoEmergenciaNombre,
    string? ContactoEmergenciaTelefono,
    string? Observaciones,
    bool Estado);

public sealed record UpsertNominaEmpleadoRequest(
    string TipoDocumento,
    string NumeroDocumento,
    DateTime? FechaExpedicionDocumento,
    string PrimerNombre,
    string? SegundoNombre,
    string PrimerApellido,
    string? SegundoApellido,
    string NombreCompleto,
    string? Documento,
    DateTime? FechaNacimiento,
    string? Genero,
    string? EstadoCivil,
    string? Telefono,
    string? Correo,
    string? Direccion,
    string? Departamento,
    string? Municipio,
    string? Pais,
    string? Cargo,
    DateTime? FechaIngreso,
    DateTime? FechaRetiro,
    string? TipoContrato,
    string? TipoTrabajador,
    string? SubtipoCotizante,
    string? TipoSalario,
    bool SalarioIntegral,
    decimal SalarioBase,
    decimal ValorDiaBase,
    string? PeriodicidadPago,
    string? JornadaLaboral,
    string? Eps,
    string? FondoPension,
    string? FondoCesantias,
    string? Arl,
    string? NivelRiesgoArl,
    string? CajaCompensacion,
    string? Banco,
    string? TipoCuenta,
    string? NumeroCuenta,
    string? ContactoEmergenciaNombre,
    string? ContactoEmergenciaTelefono,
    string? Observaciones,
    bool Estado);

public sealed record NominaPeriodoDto(
    int Id,
    int EmpresaId,
    int Anio,
    int Mes,
    string Nombre,
    DateTime FechaInicio,
    DateTime FechaFin,
    int DiasConteo,
    bool Cerrado,
    bool Estado);

public sealed record NominaDiaNoLaboradoDto(int Id, DateTime Fecha, string? Motivo);

public sealed record UpsertNominaPeriodoRequest(
    int Anio,
    int Mes,
    string? Nombre,
    DateTime? FechaInicio,
    DateTime? FechaFin,
    IReadOnlyCollection<NominaDiaNoLaboradoDto>? DiasNoLaborados);

public sealed record NominaDiaDto(DateTime Fecha, string Dia, bool EsNoLaborado, string? MotivoNoLaborado);

public sealed record NominaRegistroDto(
    int Id,
    int PeriodoId,
    int EmpleadoId,
    DateTime Fecha,
    DateTime? FechaFin,
    string Concepto,
    string? TipoNovedad,
    string? CodigoNovedad,
    string EstadoDia,
    decimal? Horas,
    decimal? Porcentaje,
    decimal? BaseCalculo,
    decimal Valor,
    string? Observacion);

public sealed record UpsertNominaRegistroRequest(
    int EmpleadoId,
    DateTime Fecha,
    DateTime? FechaFin,
    string Concepto,
    string? TipoNovedad,
    string? CodigoNovedad,
    string EstadoDia,
    decimal? Horas,
    decimal? Porcentaje,
    decimal? BaseCalculo,
    decimal Valor,
    string? Observacion);

public sealed record NominaEmpleadoTotalDto(int EmpleadoId, string NombreCompleto, decimal Total);

public sealed record NominaControlDto(
    NominaPeriodoDto Periodo,
    IReadOnlyCollection<NominaEmpleadoDto> Empleados,
    IReadOnlyCollection<NominaEmpleadoDto> TodosEmpleados,
    IReadOnlyCollection<NominaDiaDto> Dias,
    IReadOnlyCollection<NominaDiaNoLaboradoDto> DiasNoLaborados,
    IReadOnlyCollection<NominaRegistroDto> Registros,
    IReadOnlyCollection<NominaEmpleadoTotalDto> TotalesEmpleado,
    decimal TotalGeneral);
